# Generated by Django 2.1.5 on 2019-02-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_serie_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='Series',
        ),
    ]
