# Generated by Django 2.1.5 on 2019-02-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20190209_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
