# Generated by Django 2.1.5 on 2019-02-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_auto_20190209_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
