# Generated by Django 2.1.5 on 2019-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_auto_20190209_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('imdb', models.CharField(blank=True, max_length=120, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('genres', models.CharField(blank=True, max_length=500, null=True)),
                ('premiered', models.CharField(blank=True, max_length=500, null=True)),
                ('scheduled', models.CharField(blank=True, max_length=500, null=True)),
                ('seasons', models.CharField(blank=True, max_length=500, null=True)),
                ('episodes', models.CharField(blank=True, max_length=500, null=True)),
                ('reviews', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
