# Generated by Django 2.1.5 on 2019-02-10 12:12

from django.db import migrations, models
import series.validators


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_tvshow_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='name',
            field=models.CharField(max_length=120, validators=[series.validators.validate_name]),
        ),
    ]
