# Generated by Django 2.1.7 on 2019-02-17 21:32

from django.db import migrations, models
import series.validators


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0011_auto_20190217_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='premiered',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='scheduled',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='seasons',
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='name',
            field=models.CharField(max_length=200, validators=[series.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='rating',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
