# Generated by Django 2.1.7 on 2019-02-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0013_auto_20190217_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='premiered',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='scheduled',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
