# Generated by Django 2.1.7 on 2019-02-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0015_tvshow_genres_spaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='genres_spaced',
        ),
    ]
