# Generated by Django 2.1.7 on 2019-02-18 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0016_remove_tvshow_genres_spaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.TVShow')),
            ],
        ),
    ]
