# Generated by Django 2.1.7 on 2019-02-18 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0017_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='tvshow',
            new_name='tvshow_id',
        ),
        migrations.AddField(
            model_name='genre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
