# Generated by Django 2.1.7 on 2019-02-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0018_auto_20190218_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='tvshow_id',
        ),
    ]
