# Generated by Django 2.1.7 on 2019-02-18 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0019_auto_20190218_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='genres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='series.Genre'),
            preserve_default=False,
        ),
    ]
