# Generated by Django 2.1.7 on 2019-02-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0020_auto_20190218_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='genres',
        ),
        migrations.AddField(
            model_name='genre',
            name='tvshows',
            field=models.ManyToManyField(to='series.TVShow'),
        ),
    ]
