# Generated by Django 2.1.7 on 2019-02-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0022_auto_20190218_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
